### ISSUE TITLE
Is this similar to Capacitor Storage?

### ISSUE THREAD

**Issue by martinsotirov** [martinkasa/capacitor-secure-storage-plugin#1]
I'm migrating a Cordova project that uses cordova-plugin-secure-storage to Capacitor, and I was wondering if this is different (more secure) than the built-in [Capacitor Storage](https://capacitor.ionicframework.com/docs/apis/storage/)?

I'm not a Swift / Java developer but upon casual inspection of Capacitor Storage's source, it seems that on iOS it's not using Keychain and on Android it's not encrypting the values in SharedPreferences like your plugin seems to be doing.

**Comment by martinkasa** [comment]
Yes, you are right. This plugin is for storing sensitive information like security tokens. Capacitor storage just store value in plain text.
