### ISSUE TITLE
plugin uses local storage instead of keychain on ios

### ISSUE THREAD

**Issue by Frotty** [martinkasa/capacitor-secure-storage-plugin#10]
I'm running a ionic project on an ios device (emulator or real) but the plugin only saves values into local storage, to be lost on app removal.

Here visible in the emulator using safari debug tools:
![](https://i.imgur.com/2exVoMH.png)

The same happens on a real device, nothing is saved to keychain.

You mentioned in another ticket that this might be related to imports - might it be a problem that I'm also using DeviceInfo import?

```
import { DeviceInfo } from '@capacitor/core';

[...]

import 'capacitor-secure-storage-plugin';
import { Plugins } from '@capacitor/core';
const { SecureStoragePlugin } = Plugins;
```

**Comment by martinkasa** [comment]
Import of the secure storage plugin seems OK, but import of DeviceInfo is not, check https://capacitor.ionicframework.com/docs/apis/device/


Regarding secure storage plugin, please check if you have something like this 
```
  pod 'CapacitorSecureStoragePlugin', :path => '../../node_modules/capacitor-secure-storage-plugin'
```

in the file ios/App/Podfile

**Comment by Frotty** [comment]
> Import of the secure storage plugin seems OK, but import of DeviceInfo is not, check > https://capacitor.ionicframework.com/docs/apis/device/

The import is only for the type in this file.

>Regarding secure storage plugin, please check if you have something like this
in the file ios/App/Podfile

Thanks, I will check tomorrow and get back to you.

**Comment by Frotty** [comment]
@martinkasa Thanks, it worked with the podfile entry and running pod install. Can you add this info to the readme? I can't see it anywhere here or on https://capacitor.ionicframework.com/docs/basics/using-plugins/

**Comment by martinkasa** [comment]
@Frotty I think it is added automatically when you run

```
npx cap sync 
````

maybe you did not run this after you installed the plugin by npm.
