### ISSUE TITLE
How to update value of key?

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [martinkasa/capacitor-secure-storage-plugin#11]
I'm trying to update value of  key(which already exist in storage). I tried,
`SecureStoragePlugin.set({key,newvalue}).then(success=>{console.log('looks like we did it')}); `
but it keeps on showing error. I don't want to first delete the key and then store it with updated value which i believe will increase the processing time. Is there any way of updating value of key without deleting it?

**Comment by martinkasa** [comment]
@GAGANsinghmsitece I have just tried it on Android and iOS as well and it works. Closing the issue, if it is still hapenning, reopen it please.
