### ISSUE TITLE
feat: add allKeys api

### ISSUE THREAD

**Issue by Badisi** [martinkasa/capacitor-secure-storage-plugin#20]
Storage implementations usually offers a way to iterate over all the entries in the storage :

- [localStorage/sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Storage) : you can combine **.length** and **.key(index)**
- [cordova-plugin-secure-storage-echo](https://www.npmjs.com/package/cordova-plugin-secure-storage-echo#get-all-keys-from-the-storage) : you can use **.keys()**

This benefits in being able to only remove the entries you were responsible for (ie. looking for entries with prefixed keys) and not remove the whole storage.

-> For iOS, SwiftKeychainWrapper already implements an [**.allKeys**](https://github.com/jrendel/SwiftKeychainWrapper/pull/90) api (missing in their doc).
-> For Android, I haven't checked yet.

**Comment by martinkasa** [comment]
Added in v0.5.0 by PR #27
