### ISSUE TITLE
Version 0.3.2 wrong capacitor dependency

### ISSUE THREAD

**Issue by jcbvm** [martinkasa/capacitor-secure-storage-plugin#21]
Version 0.3.2 is targeted for capacitor < 2.0.0, but the package.json mentions the following dependency:

"@capacitor/core": "latest"

Shouldn't this point to 1.5.x?

**Comment by martinkasa** [comment]
Yes, you are right, but since Capacitor v1 is obsolete, I am going to close this issue. You can override the capacitor version -> https://github.com/martinkasa/capacitor-secure-storage-plugin/issues/30#issuecomment-844551197
