### ISSUE TITLE
Suggestion: using session storage.

### ISSUE THREAD

**Issue by alessandroAmedei** [martinkasa/capacitor-secure-storage-plugin#26]
Is there a way to use session storage instead of local storage?

**Comment by martinkasa** [comment]
No. Just keep in mind, as is written in the description, in browser data are just obfuscated, so they can not be considered as safe.

**Comment by alessandroAmedei** [comment]
I just want to use the session storage because when the user closes the tab it will delete the storage automatically.

**Comment by martinkasa** [comment]
In that case it would work differently on web platform than in android and ios. This plugin should not be used on the web in production and if you need for development purposes delete all keys on startup, you can compine keys() and remove() methods to do so.
