### ISSUE TITLE
Error: Strong a JSON :Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by HakobiDev** [martinkasa/capacitor-secure-storage-plugin#28]
When I storing a json and stringtify it and when I pull the data from storage it will return using promise

Unexpected token o in JSON at position 1

**Comment by martinkasa** [comment]
@HakobiDev on which platform is it happening?

**Comment by HakobiDev** [comment]
> @HakobiDev on which platform is it happening?

@martinkasa ionic vue 3

**Comment by HakobiDev** [comment]
I will close it because I solved it. Thanks
