### ISSUE TITLE
iOS SecureStoragePlugin.keys() returns JSON serializable error

### ISSUE THREAD

**Issue by deepanbansal74** [martinkasa/capacitor-secure-storage-plugin#32]
Keys method return JSON Serializable Error.

**Reason:**  Return type for KeychainWrapper.allKeys() is `Set<String>`.

**QuickFix:**  File Name: Plugin/Plugin.swift

**Updated Method:** (Convert Set to Array)
```
@objc func keys(_ call: CAPPluginCall) {
        let keys = keychainwrapper.allKeys();
        call.success(["values": Array(keys)])
    }
```
   **Project Config**
  ```
 capacitor-secure-storage-plugin (0.5.0)
 @capacitor/core : 2.4.5
```
**Error Screenshot**

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/21289114/107185707-e7c56000-6a1d-11eb-8a07-9e2e4d68b9b7.png">

**Comment by martinkasa** [comment]
Thank you.
