### ISSUE TITLE
npm install capacitor-secure-storage-plugin@0.6.0 result in: No matching version found

### ISSUE THREAD

**Issue by casper5822** [martinkasa/capacitor-secure-storage-plugin#36]
Hi all,
for use with Capacitor v2 please use fixed version to 0.5.1
```
"capacitor-secure-storage-plugin": "0.5.1"
```
for Capacitor 3.0 use latest or 0.6.0
```
"capacitor-secure-storage-plugin": "^0.6.0"
```

I have tested both versions, but if you find some bug, feel free to open new issue.

_Originally posted by @martinkasa in https://github.com/martinkasa/capacitor-secure-storage-plugin/issues/30#issuecomment-846410334_

**Comment by casper5822** [comment]
I tried npm install with the new version but i'm not able to download it. 

Result is npm fail:
code ETARGET
No matching version found for capacitor-secure-storage-plugin@^0.6.0.

what am I doing wrong?

**Comment by martinkasa** [comment]
Hi, wait few minutes please, the version is already uploaded, but it takes longer than I thought for npm repository make it public. It will appear here in "Versions" tab once it is published 
https://www.npmjs.com/package/capacitor-secure-storage-plugin

**Comment by casper5822** [comment]
Sorry, thank you for all @martinkasa
