### ISSUE TITLE
register plugin on Android

### ISSUE THREAD

**Issue by pzontrop** [martinkasa/capacitor-secure-storage-plugin#37]
In the documentation it states to include the plugin in the mainActivity as such:
```
@Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(SecureStoragePlugin.class);
    }});
  }
```

However in the [upgrade guide](https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading) of capacitor 3 it states we no longer need to register plugins that way.

Is it still required to register this plugin in capacitor 3 or not?

**Comment by martinkasa** [comment]
Thanks, I missed that. I will try it and update the documentation.

**Comment by Sampath-Lokuge** [comment]
Hi @martinkasa 

Please update the doc. I can see still it is there. Thanks!
