### ISSUE TITLE
Linting error during build for Android

### ISSUE THREAD

**Issue by sampaxk** [martinkasa/capacitor-secure-storage-plugin#42]
I've installed the plugin on a new Ionic/Capacitor project, removed the android platform and re-created it with `npx cap add android`.
When I launch `./gradlew build` inside the android folder, I get an error for the task ":capacitor-secure-storage-plugin:lint".
Here is the log file of the build: [build.log](https://github.com/martinkasa/capacitor-secure-storage-plugin/files/8161988/build.log)

This is the software I use:
- Node v14.17.0
- npm v6.14.13
- Gradle 7.0

This is the package.json of the project:
`{
  "name": "openalpr",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "@awesome-cordova-plugins/core": "^5.39.0",
    "@awesome-cordova-plugins/openalpr": "^5.39.0",
    "@capacitor/android": "^3.4.0",
    "@capacitor/camera": "^1.2.4",
    "@capacitor/core": "^3.4.0",
    "@ionic/angular": "^6.0.0",
    "capacitor-secure-storage-plugin": "^0.6.2",
    "cordova-plugin-camera-preview": "^0.12.3",
    "cordova-plugin-openalpr": "^2.1.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.0.1",
    "@angular-eslint/builder": "~13.0.1",
    "@angular-eslint/eslint-plugin": "~13.0.1",
    "@angular-eslint/eslint-plugin-template": "~13.0.1",
    "@angular-eslint/template-parser": "~13.0.1",
    "@angular/cli": "~13.0.1",
    "@angular/compiler": "~13.0.0",
    "@angular/compiler-cli": "~13.0.0",
    "@angular/language-service": "~13.0.0",
    "@capacitor/cli": "^3.4.0",
    "@ionic/angular-toolkit": "^5.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "5.3.0",
    "@typescript-eslint/parser": "5.3.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "serve": "^13.0.2",
    "ts-node": "~8.3.0",
    "typescript": "~4.4.4"
  },
  "description": "An Ionic project"
}`

**Comment by martinkasa** [comment]
Today I published v0.7.0 based on the latest Capacitor plugin template, so it should be fixed.
