### ISSUE TITLE
Question: new key generation

### ISSUE THREAD

**Issue by makokev** [martinkasa/capacitor-secure-storage-plugin#52]
Hi, I like this plugin so much. Thanks for your great work!

I have a question:
It would be nice to be able to create new symmetric and asymmetric keys directly with this plugin.
I have not found a plugin to do that jet, and this one seems to be the proper one.
It would be possibile to have this feature implemented?
For Android and iOS should be quite simple, not sure about the web compatibility.

Thanks in avance!

**Comment by martinkasa** [comment]
Hi @makokev, sorry, but I do not have enough time to add major features. If you want you can try to implement it and create a PR.
