### ISSUE TITLE
How to Register Plugin in Android studio

### ISSUE THREAD

**Issue by mcroni** [martinkasa/capacitor-secure-storage-plugin#6]
wondering how to add this plugin in android studio since the class needed isnt referenced in the readme, Thank you

**Comment by martinkasa** [comment]
Hi @mcroni,

there is a link in the README https://github.com/martinkasa/capacitor-secure-storage-plugin#android
which get you to Ionic docs where they explain how ro register a plugin.


> Android
> In Android you have to register plugins manually in MainActivity class of your app.
> 
> https://capacitor.ionicframework.com/docs/plugins/android/#export-to-capacitor
