### ISSUE TITLE
What is the package name for Android Studio?

### ISSUE THREAD

**Issue by derLalla** [martinkasa/capacitor-secure-storage-plugin#7]
Hey Martinkasa,
which package import do I need to reference SecureStoragePlugin.class? I can't find the package name.

In your provided example the import is missing, and I can't figure out what package import I need..

> ```
> public class MainActivity extends BridgeActivity {
>   @Override
>   public void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
> 
>     // Initializes the Bridge
>     this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
>       // Additional plugins you've installed go here
>       // Ex: add(TotallyAwesomePlugin.class);
>       add(SecureStoragePlugin.class);
>     }});
>   }
> }
> ```

**Comment by martinkasa** [comment]
```
import com.whitestein.securestorage.SecureStoragePlugin;
```
I will add it to docs.

**Comment by derLalla** [comment]
Yes that did it. Thank you for your fast response.
