### ISSUE TITLE
Capacitor 5 compatibility

### ISSUE THREAD

**Issue by chrisweight-elsewhen** [martinkasa/capacitor-secure-storage-plugin#77]
Capacitor 5 will require some updates, including adding the namespace to [android](https://github.com/martinkasa/capacitor-secure-storage-plugin/tree/master/android)
/build.gradle

**Comment by Nazirovich** [comment]
Any progress concerning Cap 5 compatibilty?

**Comment by martinkasa** [comment]
Hi all, v0.9.0 was just published with Capacitor v5 support.
