### ISSUE TITLE
Do we need to declare compliance on Apple Store?

### ISSUE THREAD

**Issue by gerritvanaaken** [martinkasa/capacitor-secure-storage-plugin#84]
Apple forces me to declare the state of encryption for our app. Using your plugin, do we have "non-exempt" encryption algorithms? Just to be sure …

https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations

Thanks for a quick answer :-)

**Comment by martinkasa** [comment]
I use "no". it uses build in keychain.
