### ISSUE TITLE
Get method does not throw error on missing value

### ISSUE THREAD

**Issue by Frotty** [martinkasa/capacitor-secure-storage-plugin#9]
Using capacitor 1.4.0 I copied the code examples from the readme:

```
import 'capacitor-secure-storage-plugin';
import { Plugins } from '@capacitor/core';
const { SecureStoragePlugin } = Plugins;

[...]

    const key = 'moots_token_secure';
    SecureStoragePlugin.get({ key })
    .then((value: string) => {
      console.log(value);
    })
    .catch((error: any) => {
      console.log('Item with specified key does not exist.');
    });
```

But there is never any error thrown. If the value does not exist, a weird `{value: "ée"}` value is returned:
![](https://i.imgur.com/ayIDncH.png)

**Comment by martinkasa** [comment]
duplicate #2 will be fixed in next release

**Comment by Frotty** [comment]
Thanks. Do you have a rough estimate for the next release?

**Comment by Drvanon** [comment]
For me this is being quite a problem. I would be quite interested in an expected time as well.

**Comment by Frotty** [comment]
Well the next release happened, but #2 is still open

**Comment by Drvanon** [comment]
Excuse me, I got confused, I thought I was on #2 when writing this.
